### ISSUE TITLE
how to handle negative numbers....

### ISSUE THREAD

**Issue by MaudDibb** [chidiwilliams/jscheme#1]
Taking a keen interest in this project, so i did a very small tweak to include negative numbers in the scan phase.
Unfortunately, if i do that, then the '-' symbol for subtraction gets parsed as a Number with a literal value of Nan...not quite what I was hoping for. the fibonacci test fails miserably  on this as the interpreter tries to do a call on Nan. le sigh. will keep picking at it

**Comment by MaudDibb** [comment]
so i did a quick test, this seems to work:

```
default:
    let negNum = false;
    if (char == '-' && this.isDigit(this.peek())) {
        negNum = true;
	char = this.advance(); // change const char to let char at top of while loop
    }
```
then in the number parser:
```
    let literal = parseFloat(numberAsString);
    if (negNum) literal = -literal;
````

**Comment by MaudDibb** [comment]
nope....just skip the - character (and set char to next character) if the next character is a digit...parseFloat will handle the rest. oopsie ;)

**Comment by chidiwilliams** [comment]
Yeah, the tricky bit is that identifiers may also begin with the `-` symbol. So, `-32` is a number, but `-32f` is a symbol.

I've updated [the implementation](https://github.com/chidiwilliams/jscheme/commit/98e69b0a096988a14365ccef8392939df10ba6d2) to cover that edge case as well.

```javascript
if (this.isDigit(char) || (char ===  "-" && this.isDigit(this.peek()))) {
  while (this.isDigitOrDot(this.peek())) {
    this.advance();
  }
  if (this.isDigit(char) || (!this.isIdentifier(this.peek()))) {
    const numberAsString = this.source.slice(this.start, this.current);
    const literal = parseFloat(numberAsString);
    this.addToken(TokenType.Number, literal);
    break;
  }
}
```
